export const browseDrawerStyles = {
    container:"flex flex-col gap-3 p-4 w-[320px] bg-gray-50 min-h-screen",
    input:"hidden peer",
    label:"cursor-pointer",
    card:"flex items-center justify-between bg-white border border-gray-200 rounded-lg p-4 shadow-sm transition-all duration-200 hover:shadow-md peer-checked:border-blue-500 peer-checked:bg-blue-50 peer-checked:ring-2 peer-checked:ring-blue-200",
    cardItem:"flex items-center gap-2",
    cardTitle:"text-sm font-semibold text-gray-800",
    cardBadge:"bg-blue-100 text-blue-700 text-[10px] font-semibold px-2 py-0.5 rounded-full",
    cardInfo:"bg-green-100 text-green-700 text-sm font-bold px-3 py-1 rounded-full",
    addonsContainer:"flex items-center justify-between bg-white border border-gray-200 rounded-lg p-4 shadow-sm hover:shadow-md transition-all duration-200 m-2",
    drawerHeader:"text-center text-lg font-semibold mb-4",
    noOptions:"text-gray-500 text-sm font-medium",
    addonsTitle:"text-sm font-semibold text-gray-800",
    addonsPrice:"bg-green-100 text-green-700 text-sm font-bold px-3 py-1 rounded-full",
    loadingContainer:"flex items-center justify-center h-screen",
    errorMessage:"text-red-500 text-sm font-semibold",
    drawerContent:"p-4 w-90",
    drawerContentLoading:"flex items-center justify-center h-screen",
    errorLoadingMessage:"text-red-700 mt-2 bg-red-100 border border-red-200 p-3 rounded-xl text-center text-sm font-medium"
}